class ModelName:    
    model_postVFP_powheg_normal = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Mar_17_17:23:42_CSTUL16PostVFP_powheg_normal_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_powheg_normal = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Mar_17_18:01:41_CSTUL16PreVFP_powheg_normal_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_powheg_masswindow_110140 = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Mar_17_18:11:32_CSTUL16PreVFP_powheg_masswindow_110140_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_all_samples_masswindow = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_Mar_13_23:55:38_CSTUL16PreVFP_allsamples_masswindow_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_with_sigmarvDecorr_signal_reweight = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_May_16_21:42:17_CSTUL16PreVFP_masswindow_with_sigmarvDecorr_signal_reweight__DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_all_samples_masswindow_110140 = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Thu_Mar_16_16:24:42_CSTUL16PreVFP_masswindow_110140_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_without_msweight = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_15_16:30:49_CSTUL16PreVFP_masswindow_without_msweight__DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_msweight_no_sigmawv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_May_16_22:10:55_CSTUL16PreVFP_no_masswindow_no_msweight_no_sigmawv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_msweight_no_sigmawv_sigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_May_17_02:20:02_CSTUL16PreVFP_no_masswindow_no_msweight_no_sigmawv_sigmarv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_msweight_no_sigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_May_17_03:13:56_CSTUL16PreVFP_no_masswindow_no_msweight_no_sigmarv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_no_msweight_no_sigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_May_26_15:29:15_CSTUL16PreVFP_masswindow_no_msweight_no_sigmarv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_msweight_no_vtxprob = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Thu_May_18_03:39:08_CSTUL16PreVFP_no_masswindow_no_msweight_no_vtxprob_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_msweight_combined = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/Thu_May_18_04:23:52_CST_all_combined_mass_window_with_msweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_msweight_no_sigmarv_with_sigmarvDecorr  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Sun_May_21_22:00:24_CSTUL16PreVFP_no_masswindow_no_msweight_no_sigmarv_with_sigmarvDecorr_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_no_sigmarv  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_22_04:03:04_CSTUL16PreVFP_no_masswindow_msweight_no_sigmarv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_msweight_no_sigmarv  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_22_04:32:42_CSTUL16PreVFP_masswindow_msweight_no_sigmarv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_no_sigmarv_with_sigmarvDecorr  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_22_05:19:56_CSTUL16PreVFP_no_masswindow_msweight_no_sigmarv_with_sigmarvDecorr_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_no_sigmarv_no_sigmawv  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_22_16:10:13_CSTUL16PreVFP_no_masswindow_msweight_no_sigmarv_no_sigmawv_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_W_flat_mgg  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_May_26_04:26:50_CSTUL16PreVFP_no_masswindow_msweight_W_flat_mgg_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_W_flat_mgg_only_sig122127  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_May_26_14:54:11_CSTUL16PreVFP_no_masswindow_msweight_W_flat_mgg_onlysig_122127_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_W_flat_mgg_only_pp  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_May_26_15:05:31_CSTUL16PreVFP_no_masswindow_msweight_W_flat_mgg_onlypp_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_no_sigmarvwv_with_leadsublead_sigEoverE_withmsweight  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Sun_Jun__4_04:05:04UL16PreVFP_no_masswindow_no_sigmarvwv_with_leadsublead_sigEoverE_withmsweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_with_abs_negativeweight  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Thu_Jun_15_16:04:37_CSTUL16PreVFP_no_masswindow_withmsweight_withsigmarvwv_with_abs_negativeweights_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_with_reweight_negweight  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Sun_Jun_18_18:48:07_CSTUL16PreVFP_no_masswindow_withmsweight_withsigmarvwv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_no_masswindow_msweight_with_reweight_negweight_wosigmarv  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_Jun_19_02:44:29_CSTUL16PreVFP_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"

    model_combined_mass_window_with_msweight  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/Thu_May_18_04:23:52_CST_all_combined_mass_window_with_msweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"

    model_preVFP_benmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_22_03:17:37_CSTUL16PreVFP_normal_benchmark_no_masswindow_msweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_postVFP_masswindow_without_msweight = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_15_16:30:49_CSTUL16PostVFP_masswindow_without_msweight__DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_preVFP_masswindow_without_msweight = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_15_16:30:49_CSTUL16PreVFP_masswindow_without_msweight__DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_postVFP_all_samples_masswindow = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_Mar_13_23:55:38_CSTUL16PostVFP_allsamples_masswindow_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_postVFP_masswindow_without_msweight = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_May_15_16:30:49_CSTUL16PostVFP_masswindow_without_msweight__DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_postVFP_benmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_Mar_13_22:42:24_CSTUL16PostVFP_normal_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_postVFP_no_masswindow_msweight_with_reweight_negweight_wosigmarv  = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_Jun_27_16:16:52_CSTUL16PostVFP_no_masswindow_with_msweight_nosigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"

    # UL17
    model_UL17_no_masswindow_msweight_with_reweight_negweight_wosigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Mon_Aug_14_22:57:29_CSTUL17_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL17_benmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/UL17_DiphotonXGboost_afterTune.pkl"
    # model_UL17_summer20_no_masswindow_msweight_with_reweight_negweight_wosigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Oct__6_16:48:31UL17_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL17_summer20_no_masswindow_msweight_with_reweight_negweight_wosigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Nov__1_18:30:24UL17_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL17_summer20_benchmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Oct__6_17:09:21UL17_normal_benchmark_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL17_summer20_no_masswindow_msweight_with_reweight_negweight_with_rvoverwv = '/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Thu_Nov_30_23:31:25_CSTUL17_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs_rv_wv.pkl'
    model_UL17_summer20_masswindow_msweight_with_reweight_negweight_wosigmarv = '/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Fri_Dec__1_01:07:24UL17_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl'
    model_UL17_summer20_masswindow_msweight_with_reweight_negweight_wosigmarv_50train = '/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_Dec__5_00:29:59UL17_nomasswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl'
    model_name_UL17_withsigmarv_no_masswindow_largehyperparameter = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Dec__6_17:06:22UL17_nomasswindow_withmsweight_withoutsigmarv_with_reweight_negweight_tuenedHP_DiphotonXGboost_afterTune_new_withAllSigs.pkl"

    #UL18 
    model_UL18_no_masswindow_msweight_with_reweight_negweight_wosigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Aug_16_02:14:51_CSTUL18_no_masswindow_withmsweight_withoutsigmarv_with_reweight_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL18_benchmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Mar_29_15:08:31_CSTUL18_normal_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    
    model_UL18_summer20_benchmark = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_Oct_10_22:19:49_CSTUL18_normal_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL18_summer20_no_masswindow_msweight_with_reweight_negweight_wosigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Tue_Oct_10_22:11:00_CSTUL18_no_masswindow_withmsweight_withoutsigmarv_wo_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    model_UL18_summer20_with_masswindow_msweight_with_reweight_negweight_withsigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Nov__8_16:13:14UL18_with_masswindow_withmsweight_withsigmarv_wo_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    
    model_UL18_summer20_no_masswindow_msweight_with_reweight_negweight_withsigmarv = "/hpcfs/cms/cmsgpu/zhangzhx/BDT/data/forcheck_Wed_Nov__8_16:13:14UL18_no_masswindow_withmsweight_withsigmarv_wo_negweight_DiphotonXGboost_afterTune_new_withAllSigs.pkl"
    